kind: pipeline
name: Go-Zero
type: docker

steps:

- name: user-api
  image: gghtrt520/kaniko:latest
  pull: if-not-exists
  settings:
    dockerfile: ./app/rest/user/Dockerfile
    username: 
      from_secret: username
    password: 
      from_secret: password
    tags:
      - "v1"
    when:
      branch: master
      event: [ push ]

- name: alarm-rpc
  image: plugins/docker
  pull: if-not-exists
  settings:
    dockerfile: ./app/server/alarm/Dockerfile
    username: 
      from_secret: username
    password: 
      from_secret: password
    tags:
      - "v1"
    when:
      branch: master
      event: [ push ]