kind: pipeline
name: build
type: docker

steps:
- name: user-api
  image: gghtrt520/kaniko:latest
  pull: if-not-exists
  settings:
    repo: gghtrt520/zero
    dockerfile: ./app/rest/user/Dockerfile
    username: 
      from_secret: user
    password: 
      from_secret: password
    tags:
      - "user-api"
    when:
      branch: master
      event: [ push ]

- name: alarm-rpc
  image: gghtrt520/kaniko:latest
  pull: if-not-exists
  settings:
    repo: gghtrt520/zero
    dockerfile: ./app/server/alarm/Dockerfile
    username: 
      from_secret: user
    password: 
      from_secret: password
    tags:
      - "alarm-rpc"
    when:
      branch: master
      event: [ push ]

---
kind: pipeline
type: docker
name: amd64-docker

platform:
  os: linux
  arch: amd64

steps:
  - name: manifest-docker
    pull: always
    image: gghtrt520/kaniko:latest
    settings:
      auto_tag: true
      ignore_missing: true
      username:
        from_secret: user
      password:
        from_secret: password
      spec: app/server/alarm/manifest.tmpl

---
kind: pipeline
type: docker
name: arm64-docker

platform:
  os: linux
  arch: arm64

steps:
  - name: manifest-docker
    pull: always
    image: gghtrt520/kaniko:latest
    settings:
      auto_tag: true
      ignore_missing: true
      username:
        from_secret: user
      password:
        from_secret: password
      spec: app/server/alarm/manifest.tmpl
#---
#kind: pipeline
#name: deploy
#type: docker
#
#steps:
#- name: deploy-user-api
#  image: ghcr.io/bh90210/dron8s:latest
#  pull: if-not-exists
#  settings:
#    yaml: ./deploy/user-api.yaml
#    kubeconfig:
#      from_secret: kubeconfig
#
#- name: deploy-alarm-rpc
#  image: ghcr.io/bh90210/dron8s:latest
#  pull: if-not-exists
#  settings:
#    yaml: ./deploy/user-rpc.yaml
#    kubeconfig:
#      from_secret: kubeconfig