// Code generated by goctl. DO NOT EDIT!
// Source: alarm.proto

package server

import (
	"context"

	"zlei/app/server/alarm/internal/logic/greet"
	"zlei/app/server/alarm/internal/svc"
	"zlei/app/server/alarm/proto"
)

type GreetServer struct {
	svcCtx *svc.ServiceContext
	proto.UnimplementedGreetServer
}

func NewGreetServer(svcCtx *svc.ServiceContext) *GreetServer {
	return &GreetServer{
		svcCtx: svcCtx,
	}
}

func (s *GreetServer) SayHi(ctx context.Context, in *proto.HiReq) (*proto.HiResp, error) {
	l := greetlogic.NewSayHiLogic(ctx, s.svcCtx)
	return l.SayHi(in)
}

func (s *GreetServer) SayHello(ctx context.Context, in *proto.HelloReq) (*proto.HelloResp, error) {
	l := greetlogic.NewSayHelloLogic(ctx, s.svcCtx)
	return l.SayHello(in)
}
