// Code generated by goctl. DO NOT EDIT!
// Source: alarm.proto

package client

import (
	"context"

	"zlei/app/server/alarm/proto"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	EventReq  = proto.EventReq
	EventResp = proto.EventResp
	HelloReq  = proto.HelloReq
	HelloResp = proto.HelloResp
	HiReq     = proto.HiReq
	HiResp    = proto.HiResp

	Greet interface {
		SayHi(ctx context.Context, in *HiReq, opts ...grpc.CallOption) (*HiResp, error)
		SayHello(ctx context.Context, in *HelloReq, opts ...grpc.CallOption) (*HelloResp, error)
	}

	defaultGreet struct {
		cli zrpc.Client
	}
)

func NewGreet(cli zrpc.Client) Greet {
	return &defaultGreet{
		cli: cli,
	}
}

func (m *defaultGreet) SayHi(ctx context.Context, in *HiReq, opts ...grpc.CallOption) (*HiResp, error) {
	client := proto.NewGreetClient(m.cli.Conn())
	return client.SayHi(ctx, in, opts...)
}

func (m *defaultGreet) SayHello(ctx context.Context, in *HelloReq, opts ...grpc.CallOption) (*HelloResp, error) {
	client := proto.NewGreetClient(m.cli.Conn())
	return client.SayHello(ctx, in, opts...)
}
