// Code generated by goctl. DO NOT EDIT!
// Source: alarm.proto

package server

import (
	"context"

	"zlei/app/server/alarm/internal/logic/event"
	"zlei/app/server/alarm/internal/svc"
	"zlei/app/server/alarm/proto"
)

type EventServer struct {
	svcCtx *svc.ServiceContext
	proto.UnimplementedEventServer
}

func NewEventServer(svcCtx *svc.ServiceContext) *EventServer {
	return &EventServer{
		svcCtx: svcCtx,
	}
}

func (s *EventServer) AskQuestion(ctx context.Context, in *proto.EventReq) (*proto.EventResp, error) {
	l := eventlogic.NewAskQuestionLogic(ctx, s.svcCtx)
	return l.AskQuestion(in)
}
